package controller;

import com.jfoenix.controls.JFXComboBox;
import com.jfoenix.controls.JFXDialogLayout;
import com.jfoenix.controls.JFXRadioButton;
import com.jfoenix.controls.JFXTextField;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Label;
import javafx.scene.control.RadioButton;
import javafx.scene.control.ToggleGroup;
import javafx.scene.layout.Pane;

import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.ResourceBundle;

public class CreateCustomerController implements Initializable {

    @FXML
    private JFXDialogLayout root;

    @FXML
    private Pane rootPane;

    @FXML
    private JFXComboBox<String> comboProvince;

    @FXML
    private JFXComboBox<String> comboDistrict;

    @FXML
    private JFXTextField textQuarter;

    @FXML
    private JFXTextField textStreet;

    @FXML
    private JFXTextField textDoorNumber;

    @FXML
    private JFXTextField doorPostalCode;

    @FXML
    private JFXTextField textName;

    @FXML
    private JFXTextField textPhone;

    @FXML
    private JFXRadioButton radioSingular;

    @FXML
    private JFXRadioButton radioEnterprise;

    @FXML
    private Label lblIdentityNo;

    @FXML
    private JFXTextField txtIdentityNo;

    @FXML
    private Label lblSex;

    @FXML
    private JFXComboBox<String> comboSex;

    @FXML
    private Label lblCompanyName;

    @FXML
    private JFXTextField txtCompanyName;

    private List<String> provinces;

    private HashMap<String, List<String>> districtsOfProvinces;

    private ToggleGroup individualOrEnterprise;

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        fillProvinces();
        fillDistricts();
        individualOrEnterprise = new ToggleGroup();
        radioEnterprise.setToggleGroup(individualOrEnterprise);
        radioSingular.setToggleGroup(individualOrEnterprise);
    }

    @FXML
    void selectEnterprise() {
        lblIdentityNo.setText("Vergi no");
        lblSex.setVisible(false);
        comboSex.setVisible(false);
        lblCompanyName.setVisible(true);
        txtCompanyName.setVisible(true);
    }

    @FXML
    void selectIndividual() {
        lblIdentityNo.setText("T.C.");
        lblSex.setVisible(true);
        comboSex.setVisible(true);
        lblCompanyName.setVisible(false);
        txtCompanyName.setVisible(false);
    }

    @FXML
    public void save() {
        RadioButton selected = (RadioButton) individualOrEnterprise.selectedToggleProperty().getValue();
        System.out.println(selected.getText());
    }

    @FXML
    public void listDistrictsOfProvince() {
        comboDistrict.setValue("");
        comboDistrict.getItems().setAll(districtsOfProvinces.get(comboProvince.getValue()));
    }

    @FXML
    public void closeDialog() {
        CustomerController.createCustomerDialog.close();
    }

    private void fillProvinces() {
        /*
        provinces = new ArrayList<>();
        provinces.add("Antalya");
        provinces.add("Samsun");
        provinces.add("Nevşehir");
        provinces.add("Van");
        provinces.add("Burdur");
        provinces.add("Iğdır");
        provinces.add("Sakarya");
        provinces.add("Giresun");
        provinces.add("Kilis");
        provinces.add("Zonguldak");
        provinces.add("Bilecik");
        provinces.add("Bingöl");
        provinces.add("Manisa");
        provinces.add("Kastamonu");
        provinces.add("Bitlis");
        provinces.add("Kayseri");
        provinces.add("Kars");
        provinces.add("Düzce");
        provinces.add("Muş");
        provinces.add("Çankırı");
        provinces.add("Denizli");
        provinces.add("Afyonkarahisar");
        provinces.add("Amasya");
        provinces.add("Hakkâri");
        provinces.add("Aksaray");
        provinces.add("Artvin");
        provinces.add("Çanakkale");
        provinces.add("Trabzon");
        provinces.add("Tunceli");
        provinces.add("Aydın");
        provinces.add("Konya");
        provinces.add("Bolu");
        provinces.add("Çorum");
        provinces.add("Adıyaman");
        provinces.add("Edirne");
        provinces.add("Tokat");
        provinces.add("Kırşehir");
        provinces.add("Sivas");
        provinces.add("Diyarbakır");
        provinces.add("Şanlıurfa");
        provinces.add("Elâzığ");
        provinces.add("Bursa");
        provinces.add("İzmir");
        provinces.add("Eskişehir");
        provinces.add("Erzincan");
        provinces.add("Kırklareli");
        provinces.add("Erzurum");
        provinces.add("Şırnak");
        provinces.add("Bartın");
        provinces.add("Malatya");
        provinces.add("Hatay");
        provinces.add("Niğde");
        provinces.add("Sinop");
        provinces.add("Ağrı");
        provinces.add("Karabük");
        provinces.add("Yozgat");
        provinces.add("Rize");
        provinces.add("Batman");
        provinces.add("Ardahan");
        provinces.add("Osmaniye");
        provinces.add("Kırıkkale");
        provinces.add("Ordu");
        provinces.add("Adana");
        provinces.add("Tekirdağ");
        provinces.add("İstanbul");
        provinces.add("Gaziantep");
        provinces.add("Mersin");
        provinces.add("Bayburt");
        provinces.add("Siirt");
        provinces.add("Isparta");
        provinces.add("Karaman");
        provinces.add("Ankara");
        provinces.add("Gümüşhane");
        provinces.add("Kütahya");
        provinces.add("Mardin");
        provinces.add("Muğla");
        provinces.add("Kahramanmaraş");
        provinces.add("Yalova");
        provinces.add("Kocaeli");
        provinces.add("Balıkesir");
        provinces.add("Uşak");
        provinces.sort(String::compareTo);
        */
    }

    private void fillDistricts() {
        
        /*
        districtsOfProvinces = new HashMap<>();
        districtsOfProvinces.put("Kastamonu", new ArrayList<>());
        districtsOfProvinces.put("Nevşehir", new ArrayList<>());
        districtsOfProvinces.put("Denizli", new ArrayList<>());
        districtsOfProvinces.put("Bingöl", new ArrayList<>());
        districtsOfProvinces.put("İstanbul", new ArrayList<>());
        districtsOfProvinces.put("Sakarya", new ArrayList<>());
        districtsOfProvinces.put("Adıyaman", new ArrayList<>());
        districtsOfProvinces.put("Bitlis", new ArrayList<>());
        districtsOfProvinces.put("Kahramanmaraş", new ArrayList<>());
        districtsOfProvinces.put("Afyonkarahisar", new ArrayList<>());
        districtsOfProvinces.put("Aksaray", new ArrayList<>());
        districtsOfProvinces.put("Elâzığ", new ArrayList<>());
        districtsOfProvinces.put("Burdur", new ArrayList<>());
        districtsOfProvinces.get("Kastamonu").add("Ağlı");
        districtsOfProvinces.put("Ağrı", new ArrayList<>());
        districtsOfProvinces.put("Konya", new ArrayList<>());
        districtsOfProvinces.get("Bitlis").add("Ahlat");
        districtsOfProvinces.put("Manisa", new ArrayList<>());
        districtsOfProvinces.put("Trabzon", new ArrayList<>());
        districtsOfProvinces.put("Malatya", new ArrayList<>());
        districtsOfProvinces.put("Şanlıurfa", new ArrayList<>());
        districtsOfProvinces.put("Kırşehir", new ArrayList<>());
        districtsOfProvinces.put("Düzce", new ArrayList<>());
        districtsOfProvinces.put("Yozgat", new ArrayList<>());
        districtsOfProvinces.put("Mersin", new ArrayList<>());
        districtsOfProvinces.get("Manisa").add("Akhisar");
        districtsOfProvinces.put("Sivas", new ArrayList<>());
        districtsOfProvinces.put("Kayseri", new ArrayList<>());
        districtsOfProvinces.put("Ordu", new ArrayList<>());
        districtsOfProvinces.get("Konya").add("Akören");
        districtsOfProvinces.get("Kırşehir").add("Akpınar");
        districtsOfProvinces.get("Aksaray").add("Aksaray");
        districtsOfProvinces.put("Antalya", new ArrayList<>());
        districtsOfProvinces.get("Antalya").add("Aksu");
        districtsOfProvinces.put("Isparta", new ArrayList<>());
        districtsOfProvinces.get("Konya").add("Akşehir");
        districtsOfProvinces.put("Kars", new ArrayList<>());
        districtsOfProvinces.get("Sakarya").add("Akyazı");
        districtsOfProvinces.put("Ankara", new ArrayList<>());
        districtsOfProvinces.put("Çorum", new ArrayList<>());
        districtsOfProvinces.get("Elâzığ").add("Alacakaya");
        districtsOfProvinces.put("Samsun", new ArrayList<>());
        districtsOfProvinces.put("Adana", new ArrayList<>());
        districtsOfProvinces.get("Antalya").add("Alanya");
        districtsOfProvinces.put("Zonguldak", new ArrayList<>());
        districtsOfProvinces.get("Manisa").add("Alaşehir");
        districtsOfProvinces.put("İzmir", new ArrayList<>());
        districtsOfProvinces.put("Tokat", new ArrayList<>());
        districtsOfProvinces.put("Eskişehir", new ArrayList<>());
        districtsOfProvinces.put("Balıkesir", new ArrayList<>());
        districtsOfProvinces.get("Ankara").add("Altındağ");
        districtsOfProvinces.get("Konya").add("Altınekin");
        districtsOfProvinces.get("Ordu").add("Altınordu");
        districtsOfProvinces.put("Yalova", new ArrayList<>());
        districtsOfProvinces.put("Hatay", new ArrayList<>());
        districtsOfProvinces.put("Kütahya", new ArrayList<>());
        districtsOfProvinces.get("Burdur").add("Altınyayla");
        districtsOfProvinces.get("Sivas").add("Altınyayla");
        districtsOfProvinces.put("Niğde", new ArrayList<>());
        districtsOfProvinces.put("Giresun", new ArrayList<>());
        districtsOfProvinces.put("Bartın", new ArrayList<>());
        districtsOfProvinces.put("Amasya", new ArrayList<>());
        districtsOfProvinces.get("Mersin").add("Anamur");
        districtsOfProvinces.get("Kahramanmaraş").add("Andırın");
        districtsOfProvinces.get("Hatay").add("Antakya");
        districtsOfProvinces.put("Gaziantep", new ArrayList<>());
        districtsOfProvinces.get("Kastamonu").add("Araç");
        districtsOfProvinces.get("Trabzon").add("Araklı");
        districtsOfProvinces.put("Iğdır", new ArrayList<>());
        districtsOfProvinces.get("Malatya").add("Arapgir");
        districtsOfProvinces.put("Ardahan", new ArrayList<>());
        districtsOfProvinces.put("Artvin", new ArrayList<>());
        districtsOfProvinces.put("Rize", new ArrayList<>());
        districtsOfProvinces.get("Malatya").add("Arguvan");
        districtsOfProvinces.get("Artvin").add("Arhavi");
        districtsOfProvinces.get("Elâzığ").add("Arıcak");
        districtsOfProvinces.get("Sakarya").add("Arifiye");
        districtsOfProvinces.get("Yalova").add("Armutlu");
        districtsOfProvinces.get("İstanbul").add("Arnavutköy");
        districtsOfProvinces.get("Kars").add("Arpaçay");
        districtsOfProvinces.get("Trabzon").add("Arsin");
        districtsOfProvinces.get("Hatay").add("Arsuz");
        districtsOfProvinces.get("Tokat").add("Artova");
        districtsOfProvinces.put("Mardin", new ArrayList<>());
        districtsOfProvinces.get("Artvin").add("Artvin");
        districtsOfProvinces.get("Samsun").add("Asarcık");
        districtsOfProvinces.get("Kütahya").add("Aslanapa");
        districtsOfProvinces.put("Erzurum", new ArrayList<>());
        districtsOfProvinces.get("Isparta").add("Atabey");
        districtsOfProvinces.get("Samsun").add("Atakum");
        districtsOfProvinces.get("İstanbul").add("Ataşehir");
        districtsOfProvinces.put("Çankırı", new ArrayList<>());
        districtsOfProvinces.get("Nevşehir").add("Avanos");
        districtsOfProvinces.get("İstanbul").add("Avcılar");
        districtsOfProvinces.put("Sinop", new ArrayList<>());
        districtsOfProvinces.get("Ankara").add("Ayaş");
        districtsOfProvinces.get("Ordu").add("Aybastı");
        districtsOfProvinces.get("Mersin").add("Aydıncık");
        districtsOfProvinces.get("Yozgat").add("Aydıncık");
        districtsOfProvinces.put("Bayburt", new ArrayList<>());
        districtsOfProvinces.put("Karaman", new ArrayList<>());
        districtsOfProvinces.put("Çanakkale", new ArrayList<>());
        districtsOfProvinces.get("Samsun").add("Ayvacık");
        districtsOfProvinces.get("Balıkesir").add("Ayvalık");
        districtsOfProvinces.get("Kastamonu").add("Azdavay");
        districtsOfProvinces.get("Erzurum").add("Aziziye");
        districtsOfProvinces.get("Denizli").add("Babadağ");
        districtsOfProvinces.put("Kırklareli", new ArrayList<>());
        districtsOfProvinces.get("Samsun").add("Bafra");
        districtsOfProvinces.get("İstanbul").add("Bağcılar");
        districtsOfProvinces.put("Diyarbakır", new ArrayList<>());
        districtsOfProvinces.put("Osmaniye", new ArrayList<>());
        districtsOfProvinces.get("İstanbul").add("Bahçelievler");
        districtsOfProvinces.put("Van", new ArrayList<>());
        districtsOfProvinces.put("Kırıkkale", new ArrayList<>());
        districtsOfProvinces.get("İstanbul").add("Bakırköy");
        districtsOfProvinces.get("Denizli").add("Baklan");
        districtsOfProvinces.get("Ankara").add("Bala");
        districtsOfProvinces.get("İzmir").add("Balçova");
        districtsOfProvinces.get("Kırıkkale").add("Balışeyh");
        districtsOfProvinces.get("Balıkesir").add("Balya");
        districtsOfProvinces.put("Uşak", new ArrayList<>());
        districtsOfProvinces.get("Balıkesir").add("Bandırma");
        districtsOfProvinces.get("Bartın").add("Bartın");
        districtsOfProvinces.get("Elâzığ").add("Baskil");
        districtsOfProvinces.get("İstanbul").add("Başakşehir");
        districtsOfProvinces.get("Tokat").add("Başçiftlik");
        districtsOfProvinces.put("Kocaeli", new ArrayList<>());
        districtsOfProvinces.get("Van").add("Başkale");
        districtsOfProvinces.get("Afyonkarahisar").add("Başmakçı");
        districtsOfProvinces.get("Karaman").add("Başyayla");
        districtsOfProvinces.put("Batman", new ArrayList<>());
        districtsOfProvinces.get("Malatya").add("Battalgazi");
        districtsOfProvinces.get("Afyonkarahisar").add("Bayat");
        districtsOfProvinces.get("Çorum").add("Bayat");
        districtsOfProvinces.get("Bayburt").add("Bayburt");
        districtsOfProvinces.get("İzmir").add("Bayındır");
        districtsOfProvinces.put("Siirt", new ArrayList<>());
        districtsOfProvinces.get("İzmir").add("Bayraklı");
        districtsOfProvinces.get("Çanakkale").add("Bayramiç");
        districtsOfProvinces.get("Çankırı").add("Bayramören");
        districtsOfProvinces.get("İstanbul").add("Bayrampaşa");
        districtsOfProvinces.get("Denizli").add("Bekilli");
        districtsOfProvinces.get("Hatay").add("Belen");
        districtsOfProvinces.get("İzmir").add("Bergama");
        districtsOfProvinces.get("Adıyaman").add("Besni");
        districtsOfProvinces.get("Trabzon").add("Beşikdüzü");
        districtsOfProvinces.get("İstanbul").add("Beşiktaş");
        districtsOfProvinces.get("Batman").add("Beşiri");
        districtsOfProvinces.get("Denizli").add("Beyağaç");
        districtsOfProvinces.get("İzmir").add("Beydağ");
        districtsOfProvinces.get("İstanbul").add("Beykoz");
        districtsOfProvinces.get("İstanbul").add("Beylikdüzü");
        districtsOfProvinces.get("Eskişehir").add("Beylikova");
        districtsOfProvinces.get("İstanbul").add("Beyoğlu");
        districtsOfProvinces.get("Ankara").add("Beypazarı");
        districtsOfProvinces.get("Konya").add("Beyşehir");
        districtsOfProvinces.put("Şırnak", new ArrayList<>());
        districtsOfProvinces.get("Çanakkale").add("Biga");
        districtsOfProvinces.get("Balıkesir").add("Bigadiç");
        districtsOfProvinces.put("Bilecik", new ArrayList<>());
        districtsOfProvinces.get("Bingöl").add("Bingöl");
        districtsOfProvinces.get("Şanlıurfa").add("Birecik");
        districtsOfProvinces.get("Diyarbakır").add("Bismil");
        districtsOfProvinces.get("Bitlis").add("Bitlis");
        districtsOfProvinces.put("Muğla", new ArrayList<>());
        districtsOfProvinces.get("Çorum").add("Boğazkale");
        districtsOfProvinces.get("Yozgat").add("Boğazlıyan");
        districtsOfProvinces.put("Bolu", new ArrayList<>());
        districtsOfProvinces.get("Afyonkarahisar").add("Bolvadin");
        districtsOfProvinces.get("Niğde").add("Bor");
        districtsOfProvinces.get("Artvin").add("Borçka");
        districtsOfProvinces.get("İzmir").add("Bornova");
        districtsOfProvinces.get("Sinop").add("Boyabat");
        districtsOfProvinces.get("Çanakkale").add("Bozcaada");
        districtsOfProvinces.put("Aydın", new ArrayList<>());
        districtsOfProvinces.get("Konya").add("Bozkır");
        districtsOfProvinces.get("Denizli").add("Bozkurt");
        districtsOfProvinces.get("Kastamonu").add("Bozkurt");
        districtsOfProvinces.get("Şanlıurfa").add("Bozova");
        districtsOfProvinces.get("Kırşehir").add("Boztepe");
        districtsOfProvinces.get("Bilecik").add("Bozüyük");
        districtsOfProvinces.get("Mersin").add("Bozyazı");
        districtsOfProvinces.get("İzmir").add("Buca");
        districtsOfProvinces.get("Burdur").add("Bucak");
        districtsOfProvinces.get("Aydın").add("Buharkent");
        districtsOfProvinces.get("Giresun").add("Bulancak");
        districtsOfProvinces.put("Muş", new ArrayList<>());
        districtsOfProvinces.get("Denizli").add("Buldan");
        districtsOfProvinces.get("Burdur").add("Burdur");
        districtsOfProvinces.get("Balıkesir").add("Burhaniye");
        districtsOfProvinces.get("Kayseri").add("Bünyan");
        districtsOfProvinces.get("İstanbul").add("Büyükçekmece");
        districtsOfProvinces.put("Bursa", new ArrayList<>());
        districtsOfProvinces.get("Samsun").add("Canik");
        districtsOfProvinces.get("Adana").add("Ceyhan");
        districtsOfProvinces.get("Şanlıurfa").add("Ceylanpınar");
        districtsOfProvinces.get("Kastamonu").add("Cide");
        districtsOfProvinces.get("Konya").add("Cihanbeyli");
        districtsOfProvinces.get("Şırnak").add("Cizre");
        districtsOfProvinces.get("Düzce").add("Cumayeri");
        districtsOfProvinces.get("Kahramanmaraş").add("Çağlayancerit");
        districtsOfProvinces.get("Denizli").add("Çal");
        districtsOfProvinces.get("Van").add("Çaldıran");
        districtsOfProvinces.get("Niğde").add("Çamardı");
        districtsOfProvinces.get("Ordu").add("Çamaş");
        districtsOfProvinces.get("Denizli").add("Çameli");
        districtsOfProvinces.get("Ankara").add("Çamlıdere");
        districtsOfProvinces.get("Rize").add("Çamlıhemşin");
        districtsOfProvinces.get("Mersin").add("Çamlıyayla");
        districtsOfProvinces.get("Giresun").add("Çamoluk");
        districtsOfProvinces.get("Çanakkale").add("Çan");
        districtsOfProvinces.get("Giresun").add("Çanakçı");
        districtsOfProvinces.get("Çanakkale").add("Çanakkale");
        districtsOfProvinces.get("Yozgat").add("Çandır");
        districtsOfProvinces.get("Ankara").add("Çankaya");
        districtsOfProvinces.get("Çankırı").add("Çankırı");
        districtsOfProvinces.get("Denizli").add("Çardak");
        districtsOfProvinces.get("Samsun").add("Çarşamba");
        districtsOfProvinces.get("Trabzon").add("Çarşıbaşı");
        districtsOfProvinces.get("Erzurum").add("Çat");
        districtsOfProvinces.get("Van").add("Çatak");
        districtsOfProvinces.get("İstanbul").add("Çatalca");
        districtsOfProvinces.get("Ordu").add("Çatalpınar");
        districtsOfProvinces.get("Kastamonu").add("Çatalzeytin");
        districtsOfProvinces.get("Kütahya").add("Çavdarhisar");
        districtsOfProvinces.get("Burdur").add("Çavdır");
        districtsOfProvinces.get("Afyonkarahisar").add("Çay");
        districtsOfProvinces.get("Ordu").add("Çaybaşı");
        districtsOfProvinces.get("Zonguldak").add("Çaycuma");
        districtsOfProvinces.get("Rize").add("Çayeli");
        districtsOfProvinces.get("Yozgat").add("Çayıralan");
        districtsOfProvinces.put("Erzincan", new ArrayList<>());
        districtsOfProvinces.get("Kocaeli").add("Çayırova");
        districtsOfProvinces.get("Trabzon").add("Çaykara");
        districtsOfProvinces.get("Yozgat").add("Çekerek");
        districtsOfProvinces.get("İstanbul").add("Çekmeköy");
        districtsOfProvinces.get("Kırıkkale").add("Çelebi");
        districtsOfProvinces.get("Adıyaman").add("Çelikhan");
        districtsOfProvinces.get("Konya").add("Çeltik");
        districtsOfProvinces.get("Burdur").add("Çeltikçi");
        districtsOfProvinces.put("Tunceli", new ArrayList<>());
        districtsOfProvinces.get("Çankırı").add("Çerkeş");
        districtsOfProvinces.put("Tekirdağ", new ArrayList<>());
        districtsOfProvinces.get("Diyarbakır").add("Çermik");
        districtsOfProvinces.get("İzmir").add("Çeşme");
        districtsOfProvinces.get("Ardahan").add("Çıldır");
        districtsOfProvinces.get("Diyarbakır").add("Çınar");
        districtsOfProvinces.get("Yalova").add("Çınarcık");
        districtsOfProvinces.get("Kırşehir").add("Çiçekdağı");
        districtsOfProvinces.get("Eskişehir").add("Çifteler");
        districtsOfProvinces.get("Niğde").add("Çiftlik");
        districtsOfProvinces.get("Yalova").add("Çiftlikköy");
        districtsOfProvinces.get("İzmir").add("Çiğli");
        districtsOfProvinces.get("Düzce").add("Çilimli");
        districtsOfProvinces.get("Aydın").add("Çine");
        districtsOfProvinces.get("Denizli").add("Çivril");
        districtsOfProvinces.get("Afyonkarahisar").add("Çobanlar");
        districtsOfProvinces.get("Tekirdağ").add("Çorlu");
        districtsOfProvinces.get("Çorum").add("Çorum");
        districtsOfProvinces.get("Ankara").add("Çubuk");
        districtsOfProvinces.put("Hakkâri", new ArrayList<>());
        districtsOfProvinces.get("Adana").add("Çukurova");
        districtsOfProvinces.get("Konya").add("Çumra");
        districtsOfProvinces.get("Diyarbakır").add("Çüngüş");
        districtsOfProvinces.get("Kastamonu").add("Daday");
        districtsOfProvinces.get("Muğla").add("Dalaman");
        districtsOfProvinces.get("Ardahan").add("Damal");
        districtsOfProvinces.get("Malatya").add("Darende");
        districtsOfProvinces.get("Mardin").add("Dargeçit");
        districtsOfProvinces.get("Kocaeli").add("Darıca");
        districtsOfProvinces.get("Muğla").add("Datça");
        districtsOfProvinces.get("Afyonkarahisar").add("Dazkırı");
        districtsOfProvinces.get("Hatay").add("Defne");
        districtsOfProvinces.get("Kırıkkale").add("Delice");
        districtsOfProvinces.get("Manisa").add("Demirci");
        districtsOfProvinces.get("Kırklareli").add("Demirköy");
        districtsOfProvinces.get("Bayburt").add("Demirözü");
        districtsOfProvinces.get("Antalya").add("Demre");
        districtsOfProvinces.get("Konya").add("Derbent");
        districtsOfProvinces.get("Konya").add("Derebucak");
        districtsOfProvinces.get("Giresun").add("Dereli");
        districtsOfProvinces.get("Rize").add("Derepazarı");
        districtsOfProvinces.get("Mardin").add("Derik");
        districtsOfProvinces.get("Kocaeli").add("Derince");
        districtsOfProvinces.get("Nevşehir").add("Derinkuyu");
        districtsOfProvinces.get("Trabzon").add("Dernekpazarı");
        districtsOfProvinces.get("Kayseri").add("Develi");
        districtsOfProvinces.get("Zonguldak").add("Devrek");
        districtsOfProvinces.get("Kastamonu").add("Devrekani");
        districtsOfProvinces.get("Diyarbakır").add("Dicle");
        districtsOfProvinces.get("Aydın").add("Didim");
        districtsOfProvinces.get("Kars").add("Digor");
        districtsOfProvinces.get("İzmir").add("Dikili");
        districtsOfProvinces.get("Sinop").add("Dikmen");
        districtsOfProvinces.get("Kocaeli").add("Dilovası");
        districtsOfProvinces.get("Afyonkarahisar").add("Dinar");
        districtsOfProvinces.get("Sivas").add("Divriği");
        districtsOfProvinces.get("Ağrı").add("Diyadin");
        districtsOfProvinces.get("Çorum").add("Dodurga");
        districtsOfProvinces.get("Konya").add("Doğanhisar");
        districtsOfProvinces.get("Giresun").add("Doğankent");
        districtsOfProvinces.get("Sivas").add("Doğanşar");
        districtsOfProvinces.get("Malatya").add("Doğanşehir");
        districtsOfProvinces.get("Malatya").add("Doğanyol");
        districtsOfProvinces.get("Kastamonu").add("Doğanyurt");
        districtsOfProvinces.get("Ağrı").add("Doğubayazıt");
        districtsOfProvinces.get("Kütahya").add("Domaniç");
        districtsOfProvinces.get("Bolu").add("Dörtdivan");
        districtsOfProvinces.get("Hatay").add("Dörtyol");
        districtsOfProvinces.get("Antalya").add("Döşemealtı");
        districtsOfProvinces.get("Kahramanmaraş").add("Dulkadiroğlu");
        districtsOfProvinces.get("Kütahya").add("Dumlupınar");
        districtsOfProvinces.get("Sinop").add("Durağan");
        districtsOfProvinces.get("Balıkesir").add("Dursunbey");
        districtsOfProvinces.get("Düzce").add("Düzce");
        districtsOfProvinces.get("Osmaniye").add("Düziçi");
        districtsOfProvinces.get("Trabzon").add("Düzköy");
        districtsOfProvinces.get("Çanakkale").add("Eceabat");
        districtsOfProvinces.put("Edirne", new ArrayList<>());
        districtsOfProvinces.get("Balıkesir").add("Edremit");
        districtsOfProvinces.get("Van").add("Edremit");
        districtsOfProvinces.get("Aydın").add("Efeler");
        districtsOfProvinces.put("Karabük", new ArrayList<>());
        districtsOfProvinces.get("Diyarbakır").add("Eğil");
        districtsOfProvinces.get("Isparta").add("Eğirdir");
        districtsOfProvinces.get("Kahramanmaraş").add("Ekinözü");
        districtsOfProvinces.get("Elâzığ").add("Elazığ");
        districtsOfProvinces.put("Kilis", new ArrayList<>());
        districtsOfProvinces.get("Kahramanmaraş").add("Elbistan");
        districtsOfProvinces.get("Çankırı").add("Eldivan");
        districtsOfProvinces.get("Ağrı").add("Eleşkirt");
        districtsOfProvinces.get("Ankara").add("Elmadağ");
        districtsOfProvinces.get("Antalya").add("Elmalı");
        districtsOfProvinces.get("Kütahya").add("Emet");
        districtsOfProvinces.get("Afyonkarahisar").add("Emirdağ");
        districtsOfProvinces.get("Konya").add("Emirgazi");
        districtsOfProvinces.get("Edirne").add("Enez");
        districtsOfProvinces.get("Tokat").add("Erbaa");
        districtsOfProvinces.get("Van").add("Erciş");
        districtsOfProvinces.get("Balıkesir").add("Erdek");
        districtsOfProvinces.get("Mersin").add("Erdemli");
        districtsOfProvinces.get("Konya").add("Ereğli");
        districtsOfProvinces.get("Zonguldak").add("Ereğli");
        districtsOfProvinces.get("Sakarya").add("Erenler");
        districtsOfProvinces.get("Sinop").add("Erfelek");
        districtsOfProvinces.get("Diyarbakır").add("Ergani");
        districtsOfProvinces.get("Tekirdağ").add("Ergene");
        districtsOfProvinces.get("Karaman").add("Ermenek");
        districtsOfProvinces.get("Siirt").add("Eruh");
        districtsOfProvinces.get("Hatay").add("Erzin");
        districtsOfProvinces.get("Erzincan").add("Erzincan");
        districtsOfProvinces.get("İstanbul").add("Esenler");
        districtsOfProvinces.get("İstanbul").add("Esenyurt");
        districtsOfProvinces.get("Aksaray").add("Eskil");
        districtsOfProvinces.get("Karabük").add("Eskipazar");
        districtsOfProvinces.get("Giresun").add("Espiye");
        districtsOfProvinces.get("Uşak").add("Eşme");
        districtsOfProvinces.get("Ankara").add("Etimesgut");
        districtsOfProvinces.get("Afyonkarahisar").add("Evciler");
        districtsOfProvinces.get("Ankara").add("Evren");
        districtsOfProvinces.get("Giresun").add("Eynesil");
        districtsOfProvinces.get("İstanbul").add("Eyüp");
        districtsOfProvinces.get("Şanlıurfa").add("Eyyübiye");
        districtsOfProvinces.get("Çanakkale").add("Ezine");
        districtsOfProvinces.get("İstanbul").add("Fatih");
        districtsOfProvinces.get("Ordu").add("Fatsa");
        districtsOfProvinces.get("Adana").add("Feke");
        districtsOfProvinces.get("Kayseri").add("Felahiye");
        districtsOfProvinces.get("Sakarya").add("Ferizli");
        districtsOfProvinces.get("Muğla").add("Fethiye");
        districtsOfProvinces.get("Rize").add("Fındıklı");
        districtsOfProvinces.get("Antalya").add("Finike");
        districtsOfProvinces.get("İzmir").add("Foça");
        districtsOfProvinces.get("İzmir").add("Gaziemir");
        districtsOfProvinces.get("İstanbul").add("Gaziosmanpaşa");
        districtsOfProvinces.get("Antalya").add("Gazipaşa");
        districtsOfProvinces.get("Kocaeli").add("Gebze");
        districtsOfProvinces.get("Kütahya").add("Gediz");
        districtsOfProvinces.get("Isparta").add("Gelendost");
        districtsOfProvinces.get("Çanakkale").add("Gelibolu");
        districtsOfProvinces.get("Sivas").add("Gemerek");
        districtsOfProvinces.get("Bursa").add("Gemlik");
        districtsOfProvinces.get("Bingöl").add("Genç");
        districtsOfProvinces.get("Batman").add("Gercüş");
        districtsOfProvinces.get("Bolu").add("Gerede");
        districtsOfProvinces.get("Adıyaman").add("Gerger");
        districtsOfProvinces.get("Aydın").add("Germencik");
        districtsOfProvinces.get("Sinop").add("Gerze");
        districtsOfProvinces.get("Van").add("Gevaş");
        districtsOfProvinces.get("Sakarya").add("Geyve");
        districtsOfProvinces.get("Giresun").add("Giresun");
        districtsOfProvinces.get("Çanakkale").add("Gökçeada");
        districtsOfProvinces.get("Zonguldak").add("Gökçebey");
        districtsOfProvinces.get("Kahramanmaraş").add("Göksun");
        districtsOfProvinces.get("Adıyaman").add("Gölbaşı");
        districtsOfProvinces.get("Ankara").add("Gölbaşı");
        districtsOfProvinces.get("Kocaeli").add("Gölcük");
        districtsOfProvinces.get("Ardahan").add("Göle");
        districtsOfProvinces.get("Burdur").add("Gölhisar");
        districtsOfProvinces.get("Ordu").add("Gölköy");
        districtsOfProvinces.get("Manisa").add("Gölmarmara");
        districtsOfProvinces.get("Sivas").add("Gölova");
        districtsOfProvinces.get("Bilecik").add("Gölpazarı");
        districtsOfProvinces.get("Düzce").add("Gölyaka");
        districtsOfProvinces.get("Balıkesir").add("Gömeç");
        districtsOfProvinces.get("Balıkesir").add("Gönen");
        districtsOfProvinces.get("Isparta").add("Gönen");
        districtsOfProvinces.get("Manisa").add("Gördes");
        districtsOfProvinces.get("Giresun").add("Görele");
        districtsOfProvinces.get("Amasya").add("Göynücek");
        districtsOfProvinces.get("Bolu").add("Göynük");
        districtsOfProvinces.get("Giresun").add("Güce");
        districtsOfProvinces.get("Şırnak").add("Güçlükonak");
        districtsOfProvinces.get("Ankara").add("Güdül");
        districtsOfProvinces.get("Aksaray").add("Gülağaç");
        districtsOfProvinces.get("Mersin").add("Gülnar");
        districtsOfProvinces.get("Nevşehir").add("Gülşehir");
        districtsOfProvinces.get("Ordu").add("Gülyalı");
        districtsOfProvinces.get("Amasya").add("Gümüşhacıköy");
        districtsOfProvinces.put("Gümüşhane", new ArrayList<>());
        districtsOfProvinces.get("Düzce").add("Gümüşova");
        districtsOfProvinces.get("Antalya").add("Gündoğmuş");
        districtsOfProvinces.get("Denizli").add("Güney");
        districtsOfProvinces.get("Konya").add("Güneysınır");
        districtsOfProvinces.get("Rize").add("Güneysu");
        districtsOfProvinces.get("İstanbul").add("Güngören");
        districtsOfProvinces.get("Eskişehir").add("Günyüzü");
        districtsOfProvinces.get("Ordu").add("Gürgentepe");
        districtsOfProvinces.get("Bitlis").add("Güroymak");
        districtsOfProvinces.get("Van").add("Gürpınar");
        districtsOfProvinces.get("Bursa").add("Gürsu");
        districtsOfProvinces.get("Sivas").add("Gürün");
        districtsOfProvinces.get("İzmir").add("Güzelbahçe");
        districtsOfProvinces.get("Aksaray").add("Güzelyurt");
        districtsOfProvinces.get("Nevşehir").add("Hacıbektaş");
        districtsOfProvinces.get("Kayseri").add("Hacılar");
        districtsOfProvinces.get("Konya").add("Hadim");
        districtsOfProvinces.get("Sivas").add("Hafik");
        districtsOfProvinces.get("Hakkâri").add("Hakkâri");
        districtsOfProvinces.get("Şanlıurfa").add("Halfeti");
        districtsOfProvinces.get("Şanlıurfa").add("Haliliye");
        districtsOfProvinces.get("Konya").add("Halkapınar");
        districtsOfProvinces.get("Amasya").add("Hamamözü");
        districtsOfProvinces.get("Ağrı").add("Hamur");
        districtsOfProvinces.get("Eskişehir").add("Han");
        districtsOfProvinces.get("Ardahan").add("Hanak");
        districtsOfProvinces.get("Diyarbakır").add("Hani");
        districtsOfProvinces.get("Kastamonu").add("Hanönü");
        districtsOfProvinces.get("Bursa").add("Harmancık");
        districtsOfProvinces.get("Şanlıurfa").add("Harran");
        districtsOfProvinces.get("Osmaniye").add("Hasanbeyli");
        districtsOfProvinces.get("Batman").add("Hasankeyf");
        districtsOfProvinces.get("Muş").add("Hasköy");
        districtsOfProvinces.get("Hatay").add("Hassa");
        districtsOfProvinces.get("Balıkesir").add("Havran");
        districtsOfProvinces.get("Edirne").add("Havsa");
        districtsOfProvinces.get("Samsun").add("Havza");
        districtsOfProvinces.get("Ankara").add("Haymana");
        districtsOfProvinces.get("Tekirdağ").add("Hayrabolu");
        districtsOfProvinces.get("Trabzon").add("Hayrat");
        districtsOfProvinces.get("Diyarbakır").add("Hazro");
        districtsOfProvinces.get("Malatya").add("Hekimhan");
        districtsOfProvinces.get("Rize").add("Hemşin");
        districtsOfProvinces.get("Sakarya").add("Hendek");
        districtsOfProvinces.get("Erzurum").add("Hınıs");
        districtsOfProvinces.get("Şanlıurfa").add("Hilvan");
        districtsOfProvinces.get("Kütahya").add("Hisarcık");
        districtsOfProvinces.get("Bitlis").add("Hizan");
        districtsOfProvinces.get("Afyonkarahisar").add("Hocalar");
        districtsOfProvinces.get("Denizli").add("Honaz");
        districtsOfProvinces.get("Artvin").add("Hopa");
        districtsOfProvinces.get("Erzurum").add("Horasan");
        districtsOfProvinces.get("Tunceli").add("Hozat");
        districtsOfProvinces.get("Konya").add("Hüyük");
        districtsOfProvinces.get("Iğdır").add("Iğdır");
        districtsOfProvinces.get("Çankırı").add("Ilgaz");
        districtsOfProvinces.get("Konya").add("Ilgın");
        districtsOfProvinces.get("Isparta").add("Isparta");
        districtsOfProvinces.get("Antalya").add("İbradı");
        districtsOfProvinces.get("Şırnak").add("İdil");
        districtsOfProvinces.get("Kastamonu").add("İhsangazi");
        districtsOfProvinces.get("Afyonkarahisar").add("İhsaniye");
        districtsOfProvinces.get("Ordu").add("İkizce");
        districtsOfProvinces.get("Rize").add("İkizdere");
        districtsOfProvinces.get("Erzincan").add("İliç");
        districtsOfProvinces.get("Samsun").add("İlkadım");
        districtsOfProvinces.get("Adana").add("İmamoğlu");
        districtsOfProvinces.get("Sivas").add("İmranlı");
        districtsOfProvinces.get("Kayseri").add("İncesu");
        districtsOfProvinces.get("Aydın").add("İncirliova");
        districtsOfProvinces.get("Kastamonu").add("İnebolu");
        districtsOfProvinces.get("Bursa").add("İnegöl");
        districtsOfProvinces.get("Bilecik").add("İnhisar");
        districtsOfProvinces.get("Eskişehir").add("İnönü");
        districtsOfProvinces.get("Van").add("İpekyolu");
        districtsOfProvinces.get("Edirne").add("İpsala");
        districtsOfProvinces.get("Afyonkarahisar").add("İscehisar");
        districtsOfProvinces.get("Hatay").add("İskenderun");
        districtsOfProvinces.get("Çorum").add("İskilip");
        districtsOfProvinces.get("Gaziantep").add("İslahiye");
        districtsOfProvinces.get("Erzurum").add("İspir");
        districtsOfProvinces.get("Balıkesir").add("İvrindi");
        districtsOfProvinces.get("Rize").add("İyidere");
        districtsOfProvinces.get("Kocaeli").add("İzmit");
        districtsOfProvinces.get("Bursa").add("İznik");
        districtsOfProvinces.get("Ordu").add("Kabadüz");
        districtsOfProvinces.get("Ordu").add("Kabataş");
        districtsOfProvinces.get("İstanbul").add("Kadıköy");
        districtsOfProvinces.get("Konya").add("Kadınhanı");
        districtsOfProvinces.get("Yozgat").add("Kadışehri");
        districtsOfProvinces.get("Osmaniye").add("Kadirli");
        districtsOfProvinces.get("İstanbul").add("Kağıthane");
        districtsOfProvinces.get("Kars").add("Kağızman");
        districtsOfProvinces.get("Adıyaman").add("Kahta");
        districtsOfProvinces.get("Denizli").add("Kale");
        districtsOfProvinces.get("Malatya").add("Kale");
        districtsOfProvinces.get("Ankara").add("Kalecik");
        districtsOfProvinces.get("Rize").add("Kalkandere");
        districtsOfProvinces.get("Kırşehir").add("Kaman");
        districtsOfProvinces.get("Kocaeli").add("Kandıra");
        districtsOfProvinces.get("Sivas").add("Kangal");
        districtsOfProvinces.get("Tekirdağ").add("Kapaklı");
        districtsOfProvinces.get("İzmir").add("Karabağlar");
        districtsOfProvinces.get("İzmir").add("Karaburun");
        districtsOfProvinces.get("Karabük").add("Karabük");
        districtsOfProvinces.get("Bursa").add("Karacabey");
        districtsOfProvinces.get("Aydın").add("Karacasu");
        districtsOfProvinces.get("Erzurum").add("Karaçoban");
        districtsOfProvinces.get("Uşak").add("Karahallı");
        districtsOfProvinces.get("Adana").add("Karaisalı");
        districtsOfProvinces.get("Kırıkkale").add("Karakeçili");
        districtsOfProvinces.get("Elâzığ").add("Karakoçan");
        districtsOfProvinces.get("Iğdır").add("Karakoyunlu");
        districtsOfProvinces.get("Şanlıurfa").add("Karaköprü");
        districtsOfProvinces.get("Karaman").add("Karaman");
        districtsOfProvinces.get("Burdur").add("Karamanlı");
        districtsOfProvinces.get("Kocaeli").add("Karamürsel");
        districtsOfProvinces.get("Konya").add("Karapınar");
        districtsOfProvinces.get("Sakarya").add("Karapürçek");
        districtsOfProvinces.get("Sakarya").add("Karasu");
        districtsOfProvinces.get("Adana").add("Karataş");
        districtsOfProvinces.get("Konya").add("Karatay");
        districtsOfProvinces.get("Erzurum").add("Karayazı");
        districtsOfProvinces.get("Balıkesir").add("Karesi");
        districtsOfProvinces.get("Çorum").add("Kargı");
        districtsOfProvinces.get("Gaziantep").add("Karkamış");
        districtsOfProvinces.get("Bingöl").add("Karlıova");
        districtsOfProvinces.get("Aydın").add("Karpuzlu");
        districtsOfProvinces.get("Kars").add("Kars");
        districtsOfProvinces.get("İzmir").add("Karşıyaka");
        districtsOfProvinces.get("İstanbul").add("Kartal");
        districtsOfProvinces.get("Kocaeli").add("Kartepe");
        districtsOfProvinces.get("Kastamonu").add("Kastamonu");
        districtsOfProvinces.get("Antalya").add("Kaş");
        districtsOfProvinces.get("Samsun").add("Kavak");
        districtsOfProvinces.get("Muğla").add("Kavaklıdere");
        districtsOfProvinces.get("Diyarbakır").add("Kayapınar");
        districtsOfProvinces.get("Sakarya").add("Kaynarca");
        districtsOfProvinces.get("Düzce").add("Kaynaşlı");
        districtsOfProvinces.get("Ankara").add("Kazan");
        districtsOfProvinces.get("Karaman").add("Kazımkarabekir");
        districtsOfProvinces.get("Elâzığ").add("Keban");
        districtsOfProvinces.get("Isparta").add("Keçiborlu");
        districtsOfProvinces.get("Ankara").add("Keçiören");
        districtsOfProvinces.get("Bursa").add("Keles");
        districtsOfProvinces.get("Gümüşhane").add("Kelkit");
        districtsOfProvinces.get("Erzincan").add("Kemah");
        districtsOfProvinces.get("Erzincan").add("Kemaliye");
        districtsOfProvinces.get("İzmir").add("Kemalpaşa");
        districtsOfProvinces.get("Antalya").add("Kemer");
        districtsOfProvinces.get("Burdur").add("Kemer");
        districtsOfProvinces.get("Antalya").add("Kepez");
        districtsOfProvinces.get("Balıkesir").add("Kepsut");
        districtsOfProvinces.get("Kırıkkale").add("Keskin");
        districtsOfProvinces.get("Bursa").add("Kestel");
        districtsOfProvinces.get("Edirne").add("Keşan");
        districtsOfProvinces.get("Giresun").add("Keşap");
        districtsOfProvinces.get("Bolu").add("Kıbrıscık");
        districtsOfProvinces.get("İzmir").add("Kınık");
        districtsOfProvinces.get("Hatay").add("Kırıkhan");
        districtsOfProvinces.get("Kırıkkale").add("Kırıkkale");
        districtsOfProvinces.get("Manisa").add("Kırkağaç");
        districtsOfProvinces.get("Kırklareli").add("Kırklareli");
        districtsOfProvinces.get("Kırşehir").add("Kırşehir");
        districtsOfProvinces.get("Ankara").add("Kızılcahamam");
        districtsOfProvinces.get("Çankırı").add("Kızılırmak");
        districtsOfProvinces.get("Afyonkarahisar").add("Kızılören");
        districtsOfProvinces.get("Mardin").add("Kızıltepe");
        districtsOfProvinces.get("Bingöl").add("Kiğı");
        districtsOfProvinces.get("Zonguldak").add("Kilimli");
        districtsOfProvinces.get("Kilis").add("Kilis");
        districtsOfProvinces.get("İzmir").add("Kiraz");
        districtsOfProvinces.get("Sakarya").add("Kocaali");
        districtsOfProvinces.get("Diyarbakır").add("Kocaköy");
        districtsOfProvinces.get("Kayseri").add("Kocasinan");
        districtsOfProvinces.get("Aydın").add("Koçarlı");
        districtsOfProvinces.get("Kırklareli").add("Kofçaz");
        districtsOfProvinces.get("İzmir").add("Konak");
        districtsOfProvinces.get("Antalya").add("Konyaaltı");
        districtsOfProvinces.get("Ordu").add("Korgan");
        districtsOfProvinces.get("Çankırı").add("Korgun");
        districtsOfProvinces.get("Muş").add("Korkut");
        districtsOfProvinces.get("Antalya").add("Korkuteli");
        districtsOfProvinces.get("Elâzığ").add("Kovancılar");
        districtsOfProvinces.get("Sivas").add("Koyulhisar");
        districtsOfProvinces.get("Nevşehir").add("Kozaklı");
        districtsOfProvinces.get("Adana").add("Kozan");
        districtsOfProvinces.get("Zonguldak").add("Kozlu");
        districtsOfProvinces.get("Batman").add("Kozluk");
        districtsOfProvinces.get("Manisa").add("Köprübaşı");
        districtsOfProvinces.get("Trabzon").add("Köprübaşı");
        districtsOfProvinces.get("Erzurum").add("Köprüköy");
        districtsOfProvinces.get("Kocaeli").add("Körfez");
        districtsOfProvinces.get("Gümüşhane").add("Köse");
        districtsOfProvinces.get("Aydın").add("Köşk");
        districtsOfProvinces.get("Muğla").add("Köyceğiz");
        districtsOfProvinces.get("Manisa").add("Kula");
        districtsOfProvinces.get("Diyarbakır").add("Kulp");
        districtsOfProvinces.get("Konya").add("Kulu");
        districtsOfProvinces.get("Malatya").add("Kuluncak");
        districtsOfProvinces.get("Hatay").add("Kumlu");
        districtsOfProvinces.get("Antalya").add("Kumluca");
        districtsOfProvinces.get("Ordu").add("Kumru");
        districtsOfProvinces.get("Çankırı").add("Kurşunlu");
        districtsOfProvinces.get("Siirt").add("Kurtalan");
        districtsOfProvinces.get("Bartın").add("Kurucaşile");
        districtsOfProvinces.get("Aydın").add("Kuşadası");
        districtsOfProvinces.get("Aydın").add("Kuyucak");
        districtsOfProvinces.get("İstanbul").add("Küçükçekmece");
        districtsOfProvinces.get("Kastamonu").add("Küre");
        districtsOfProvinces.get("Gümüşhane").add("Kürtün");
        districtsOfProvinces.get("Kütahya").add("Kütahya");
        districtsOfProvinces.get("Çorum").add("Laçin");
        districtsOfProvinces.get("Samsun").add("Ladik");
        districtsOfProvinces.get("Edirne").add("Lalapaşa");
        districtsOfProvinces.get("Çanakkale").add("Lapseki");
        districtsOfProvinces.get("Diyarbakır").add("Lice");
        districtsOfProvinces.get("Kırklareli").add("Lüleburgaz");
        districtsOfProvinces.get("Trabzon").add("Maçka");
        districtsOfProvinces.get("Elâzığ").add("Maden");
        districtsOfProvinces.get("Eskişehir").add("Mahmudiye");
        districtsOfProvinces.get("Muş").add("Malazgirt");
        districtsOfProvinces.get("Tekirdağ").add("Malkara");
        districtsOfProvinces.get("İstanbul").add("Maltepe");
        districtsOfProvinces.get("Ankara").add("Mamak");
        districtsOfProvinces.get("Antalya").add("Manavgat");
        districtsOfProvinces.get("Balıkesir").add("Manyas");
        districtsOfProvinces.get("Balıkesir").add("Marmara");
        districtsOfProvinces.get("Tekirdağ").add("Marmaraereğlisi");
        districtsOfProvinces.get("Muğla").add("Marmaris");
        districtsOfProvinces.get("Tunceli").add("Mazgirt");
        districtsOfProvinces.get("Mardin").add("Mazıdağı");
        districtsOfProvinces.get("Çorum").add("Mecitözü");
        districtsOfProvinces.get("Kayseri").add("Melikgazi");
        districtsOfProvinces.get("İzmir").add("Menderes");
        districtsOfProvinces.get("İzmir").add("Menemen");
        districtsOfProvinces.get("Bolu").add("Mengen");
        districtsOfProvinces.get("Muğla").add("Menteşe");
        districtsOfProvinces.get("Konya").add("Meram");
        districtsOfProvinces.get("Edirne").add("Meriç");
        districtsOfProvinces.get("Denizli").add("Merkezefendi");
        districtsOfProvinces.get("Amasya").add("Merzifon");
        districtsOfProvinces.get("Ordu").add("Mesudiye");
        districtsOfProvinces.get("Mersin").add("Mezitli");
        districtsOfProvinces.get("Mardin").add("Midyat");
        districtsOfProvinces.get("Eskişehir").add("Mihalgazi");
        districtsOfProvinces.get("Eskişehir").add("Mihalıççık");
        districtsOfProvinces.get("Muğla").add("Milas");
        districtsOfProvinces.get("Kırşehir").add("Mucur");
        districtsOfProvinces.get("Bursa").add("Mudanya");
        districtsOfProvinces.get("Bolu").add("Mudurnu");
        districtsOfProvinces.get("Van").add("Muradiye");
        districtsOfProvinces.get("Tekirdağ").add("Muratlı");
        districtsOfProvinces.get("Antalya").add("Muratpaşa");
        districtsOfProvinces.get("Artvin").add("Murgul");
        districtsOfProvinces.get("Kilis").add("Musabeyli");
        districtsOfProvinces.get("Bursa").add("Mustafakemalpaşa");
        districtsOfProvinces.get("Muş").add("Muş");
        districtsOfProvinces.get("Mersin").add("Mut");
        districtsOfProvinces.get("Bitlis").add("Mutki");
        districtsOfProvinces.get("Ankara").add("Nallıhan");
        districtsOfProvinces.get("İzmir").add("Narlıdere");
        districtsOfProvinces.get("Erzurum").add("Narman");
        districtsOfProvinces.get("Tunceli").add("Nazımiye");
        districtsOfProvinces.get("Aydın").add("Nazilli");
        districtsOfProvinces.get("Nevşehir").add("Nevşehir");
        districtsOfProvinces.get("Niğde").add("Niğde");
        districtsOfProvinces.get("Tokat").add("Niksar");
        districtsOfProvinces.get("Bursa").add("Nilüfer");
        districtsOfProvinces.get("Gaziantep").add("Nizip");
        districtsOfProvinces.get("Gaziantep").add("Nurdağı");
        districtsOfProvinces.get("Kahramanmaraş").add("Nurhak");
        districtsOfProvinces.get("Mardin").add("Nusaybin");
        districtsOfProvinces.get("Eskişehir").add("Odunpazarı");
        districtsOfProvinces.get("Trabzon").add("Of");
        districtsOfProvinces.get("Gaziantep").add("Oğuzeli");
        districtsOfProvinces.get("Çorum").add("Oğuzlar");
        districtsOfProvinces.get("Erzurum").add("Oltu");
        districtsOfProvinces.get("Erzurum").add("Olur");
        districtsOfProvinces.get("Samsun").add("Ondokuzmayıs");
        districtsOfProvinces.get("Kahramanmaraş").add("Onikişubat");
        districtsOfProvinces.get("Bursa").add("Orhaneli");
        districtsOfProvinces.get("Bursa").add("Orhangazi");
        districtsOfProvinces.get("Çankırı").add("Orta");
        districtsOfProvinces.get("Muğla").add("Ortaca");
        districtsOfProvinces.get("Trabzon").add("Ortahisar");
        districtsOfProvinces.get("Aksaray").add("Ortaköy");
        districtsOfProvinces.get("Çorum").add("Ortaköy");
        districtsOfProvinces.get("Çorum").add("Osmancık");
        districtsOfProvinces.get("Bilecik").add("Osmaneli");
        districtsOfProvinces.get("Bursa").add("Osmangazi");
        districtsOfProvinces.get("Osmaniye").add("Osmaniye");
        districtsOfProvinces.get("Erzincan").add("Otlukbeli");
        districtsOfProvinces.get("Karabük").add("Ovacık");
        districtsOfProvinces.get("Tunceli").add("Ovacık");
        districtsOfProvinces.get("İzmir").add("Ödemiş");
        districtsOfProvinces.get("Mardin").add("Ömerli");
        districtsOfProvinces.get("Van").add("Özalp");
        districtsOfProvinces.get("Kayseri").add("Özvatan");
        districtsOfProvinces.get("Erzurum").add("Palandöken");
        districtsOfProvinces.get("Elâzığ").add("Palu");
        districtsOfProvinces.get("Denizli").add("Pamukkale");
        districtsOfProvinces.get("Sakarya").add("Pamukova");
        districtsOfProvinces.get("Erzurum").add("Pasinler");
        districtsOfProvinces.get("Ağrı").add("Patnos");
        districtsOfProvinces.get("Hatay").add("Payas");
        districtsOfProvinces.get("Rize").add("Pazar");
        districtsOfProvinces.get("Tokat").add("Pazar");
        districtsOfProvinces.get("Kahramanmaraş").add("Pazarcık");
        districtsOfProvinces.get("Kütahya").add("Pazarlar");
        districtsOfProvinces.get("Bilecik").add("Pazaryeri");
        districtsOfProvinces.get("Erzurum").add("Pazaryolu");
        districtsOfProvinces.get("Kırklareli").add("Pehlivanköy");
        districtsOfProvinces.get("İstanbul").add("Pendik");
        districtsOfProvinces.get("Ordu").add("Perşembe");
        districtsOfProvinces.get("Tunceli").add("Pertek");
        districtsOfProvinces.get("Siirt").add("Pervari");
        districtsOfProvinces.get("Kastamonu").add("Pınarbaşı");
        districtsOfProvinces.get("Kayseri").add("Pınarbaşı");
        districtsOfProvinces.get("Kırklareli").add("Pınarhisar");
        districtsOfProvinces.get("Giresun").add("Piraziz");
        districtsOfProvinces.get("Kilis").add("Polateli");
        districtsOfProvinces.get("Ankara").add("Polatlı");
        districtsOfProvinces.get("Ardahan").add("Posof");
        districtsOfProvinces.get("Adana").add("Pozantı");
        districtsOfProvinces.get("Ankara").add("Pursaklar");
        districtsOfProvinces.get("Tunceli").add("Pülümür");
        districtsOfProvinces.get("Malatya").add("Pütürge");
        districtsOfProvinces.get("Erzincan").add("Refahiye");
        districtsOfProvinces.get("Tokat").add("Reşadiye");
        districtsOfProvinces.get("Hatay").add("Reyhanlı");
        districtsOfProvinces.get("Rize").add("Rize");
        districtsOfProvinces.get("Karabük").add("Safranbolu");
        districtsOfProvinces.get("Adana").add("Saimbeyli");
        districtsOfProvinces.get("Samsun").add("Salıpazarı");
        districtsOfProvinces.get("Manisa").add("Salihli");
        districtsOfProvinces.get("Hatay").add("Samandağ");
        districtsOfProvinces.get("Adıyaman").add("Samsat");
        districtsOfProvinces.get("İstanbul").add("Sancaktepe");
        districtsOfProvinces.get("Afyonkarahisar").add("Sandıklı");
        districtsOfProvinces.get("Sakarya").add("Sapanca");
        districtsOfProvinces.get("Tekirdağ").add("Saray");
        districtsOfProvinces.get("Van").add("Saray");
        districtsOfProvinces.get("Sinop").add("Saraydüzü");
        districtsOfProvinces.get("Yozgat").add("Saraykent");
        districtsOfProvinces.get("Denizli").add("Sarayköy");
        districtsOfProvinces.get("Konya").add("Sarayönü");
        districtsOfProvinces.get("Eskişehir").add("Sarıcakaya");
        districtsOfProvinces.get("Adana").add("Sarıçam");
        districtsOfProvinces.get("Manisa").add("Sarıgöl");
        districtsOfProvinces.get("Kars").add("Sarıkamış");
        districtsOfProvinces.get("Yozgat").add("Sarıkaya");
        districtsOfProvinces.get("Kayseri").add("Sarıoğlan");
        districtsOfProvinces.get("Karaman").add("Sarıveliler");
        districtsOfProvinces.get("Aksaray").add("Sarıyahşi");
        districtsOfProvinces.get("İstanbul").add("Sarıyer");
        districtsOfProvinces.get("Kayseri").add("Sarız");
        districtsOfProvinces.get("Manisa").add("Saruhanlı");
        districtsOfProvinces.get("Batman").add("Sason");
        districtsOfProvinces.get("Balıkesir").add("Savaştepe");
        districtsOfProvinces.get("Mardin").add("Savur");
        districtsOfProvinces.get("Bolu").add("Seben");
        districtsOfProvinces.get("İzmir").add("Seferihisar");
        districtsOfProvinces.get("İzmir").add("Selçuk");
        districtsOfProvinces.get("Konya").add("Selçuklu");
        districtsOfProvinces.get("Manisa").add("Selendi");
        districtsOfProvinces.get("Kars").add("Selim");
        districtsOfProvinces.get("Isparta").add("Senirkent");
        districtsOfProvinces.get("Sakarya").add("Serdivan");
        districtsOfProvinces.get("Antalya").add("Serik");
        districtsOfProvinces.get("Denizli").add("Serinhisar");
        districtsOfProvinces.get("Muğla").add("Seydikemer");
        districtsOfProvinces.get("Kastamonu").add("Seydiler");
        districtsOfProvinces.get("Konya").add("Seydişehir");
        districtsOfProvinces.get("Adana").add("Seyhan");
        districtsOfProvinces.get("Eskişehir").add("Seyitgazi");
        districtsOfProvinces.get("Balıkesir").add("Sındırgı");
        districtsOfProvinces.get("Siirt").add("Siirt");
        districtsOfProvinces.get("Mersin").add("Silifke");
        districtsOfProvinces.get("İstanbul").add("Silivri");
        districtsOfProvinces.get("Şırnak").add("Silopi");
        districtsOfProvinces.get("Diyarbakır").add("Silvan");
        districtsOfProvinces.get("Kütahya").add("Simav");
        districtsOfProvinces.get("Afyonkarahisar").add("Sinanpaşa");
        districtsOfProvinces.get("Ankara").add("Sincan");
        districtsOfProvinces.get("Adıyaman").add("Sincik");
        districtsOfProvinces.get("Sinop").add("Sinop");
        districtsOfProvinces.get("Sivas").add("Sivas");
        districtsOfProvinces.get("Uşak").add("Sivaslı");
        districtsOfProvinces.get("Şanlıurfa").add("Siverek");
        districtsOfProvinces.get("Elâzığ").add("Sivrice");
        districtsOfProvinces.get("Eskişehir").add("Sivrihisar");
        districtsOfProvinces.get("Bingöl").add("Solhan");
        districtsOfProvinces.get("Manisa").add("Soma");
        districtsOfProvinces.get("Yozgat").add("Sorgun");
        districtsOfProvinces.get("Bilecik").add("Söğüt");
        districtsOfProvinces.get("Sakarya").add("Söğütlü");
        districtsOfProvinces.get("Aydın").add("Söke");
        districtsOfProvinces.get("Kırıkkale").add("Sulakyurt");
        districtsOfProvinces.get("İstanbul").add("Sultanbeyli");
        districtsOfProvinces.get("Afyonkarahisar").add("Sultandağı");
        districtsOfProvinces.get("İstanbul").add("Sultangazi");
        districtsOfProvinces.get("Aydın").add("Sultanhisar");
        districtsOfProvinces.get("Amasya").add("Suluova");
        districtsOfProvinces.get("Tokat").add("Sulusaray");
        districtsOfProvinces.get("Osmaniye").add("Sumbas");
        districtsOfProvinces.get("Çorum").add("Sungurlu");
        districtsOfProvinces.get("Diyarbakır").add("Sur");
        districtsOfProvinces.get("Şanlıurfa").add("Suruç");
        districtsOfProvinces.get("Balıkesir").add("Susurluk");
        districtsOfProvinces.get("Kars").add("Susuz");
        districtsOfProvinces.get("Sivas").add("Suşehri");
        districtsOfProvinces.get("Tekirdağ").add("Süleymanpaşa");
        districtsOfProvinces.get("Edirne").add("Süloğlu");
        districtsOfProvinces.get("Trabzon").add("Sürmene");
        districtsOfProvinces.get("Isparta").add("Sütçüler");
        districtsOfProvinces.get("Çankırı").add("Şabanözü");
        districtsOfProvinces.get("Gaziantep").add("Şahinbey");
        districtsOfProvinces.get("Trabzon").add("Şalpazarı");
        districtsOfProvinces.get("Kütahya").add("Şaphane");
        districtsOfProvinces.get("Sivas").add("Şarkışla");
        districtsOfProvinces.get("Isparta").add("Şarkikaraağaç");
        districtsOfProvinces.get("Tekirdağ").add("Şarköy");
        districtsOfProvinces.get("Artvin").add("Şavşat");
        districtsOfProvinces.get("Giresun").add("Şebinkarahisar");
        districtsOfProvinces.get("Yozgat").add("Şefaatli");
        districtsOfProvinces.get("Gaziantep").add("Şehitkamil");
        districtsOfProvinces.get("Manisa").add("Şehzadeler");
        districtsOfProvinces.get("Hakkâri").add("Şemdinli");
        districtsOfProvinces.get("Erzurum").add("Şenkaya");
        districtsOfProvinces.get("Kastamonu").add("Şenpazar");
        districtsOfProvinces.get("Ankara").add("Şereflikoçhisar");
        districtsOfProvinces.get("Şırnak").add("Şırnak");
        districtsOfProvinces.get("İstanbul").add("Şile");
        districtsOfProvinces.get("Gümüşhane").add("Şiran");
        districtsOfProvinces.get("Siirt").add("Şirvan");
        districtsOfProvinces.get("İstanbul").add("Şişli");
        districtsOfProvinces.get("Afyonkarahisar").add("Şuhut");
        districtsOfProvinces.get("Kayseri").add("Talas");
        districtsOfProvinces.get("Sakarya").add("Taraklı");
        districtsOfProvinces.get("Mersin").add("Tarsus");
        districtsOfProvinces.get("Konya").add("Taşkent");
        districtsOfProvinces.get("Kastamonu").add("Taşköprü");
        districtsOfProvinces.get("Ağrı").add("Taşlıçay");
        districtsOfProvinces.get("Amasya").add("Taşova");
        districtsOfProvinces.get("Bitlis").add("Tatvan");
        districtsOfProvinces.get("Denizli").add("Tavas");
        districtsOfProvinces.get("Kütahya").add("Tavşanlı");
        districtsOfProvinces.get("Burdur").add("Tefenni");
        districtsOfProvinces.get("Samsun").add("Tekkeköy");
        districtsOfProvinces.get("Erzurum").add("Tekman");
        districtsOfProvinces.get("Eskişehir").add("Tepebaşı");
        districtsOfProvinces.get("Erzincan").add("Tercan");
        districtsOfProvinces.get("Yalova").add("Termal");
        districtsOfProvinces.get("Samsun").add("Terme");
        districtsOfProvinces.get("Siirt").add("Tillo");
        districtsOfProvinces.get("İzmir").add("Tire");
        districtsOfProvinces.get("Giresun").add("Tirebolu");
        districtsOfProvinces.get("Tokat").add("Tokat");
        districtsOfProvinces.get("Kayseri").add("Tomarza");
        districtsOfProvinces.get("Trabzon").add("Tonya");
        districtsOfProvinces.get("Osmaniye").add("Toprakkale");
        districtsOfProvinces.get("İzmir").add("Torbalı");
        districtsOfProvinces.get("Mersin").add("Toroslar");
        districtsOfProvinces.get("Erzurum").add("Tortum");
        districtsOfProvinces.get("Gümüşhane").add("Torul");
        districtsOfProvinces.get("Kastamonu").add("Tosya");
        districtsOfProvinces.get("Adana").add("Tufanbeyli");
        districtsOfProvinces.get("Tunceli").add("Tunceli");
        districtsOfProvinces.get("Manisa").add("Turgutlu");
        districtsOfProvinces.get("Tokat").add("Turhal");
        districtsOfProvinces.get("Van").add("Tuşba");
        districtsOfProvinces.get("Adıyaman").add("Tut");
        districtsOfProvinces.get("Ağrı").add("Tutak");
        districtsOfProvinces.get("İstanbul").add("Tuzla");
        districtsOfProvinces.get("Iğdır").add("Tuzluca");
        districtsOfProvinces.get("Konya").add("Tuzlukçu");
        districtsOfProvinces.get("Sinop").add("Türkeli");
        districtsOfProvinces.get("Kahramanmaraş").add("Türkoğlu");
        districtsOfProvinces.get("Çorum").add("Uğurludağ");
        districtsOfProvinces.get("Muğla").add("Ula");
        districtsOfProvinces.get("Sivas").add("Ulaş");
        districtsOfProvinces.get("Ordu").add("Ulubey");
        districtsOfProvinces.get("Uşak").add("Ulubey");
        districtsOfProvinces.get("Isparta").add("Uluborlu");
        districtsOfProvinces.get("Şırnak").add("Uludere");
        districtsOfProvinces.get("Niğde").add("Ulukışla");
        districtsOfProvinces.get("Bartın").add("Ulus");
        districtsOfProvinces.get("İzmir").add("Urla");
        districtsOfProvinces.get("Uşak").add("Uşak");
        districtsOfProvinces.get("Erzurum").add("Uzundere");
        districtsOfProvinces.get("Edirne").add("Uzunköprü");
        districtsOfProvinces.get("İstanbul").add("Ümraniye");
        districtsOfProvinces.get("Ordu").add("Ünye");
        districtsOfProvinces.get("Nevşehir").add("Ürgüp");
        districtsOfProvinces.get("İstanbul").add("Üsküdar");
        districtsOfProvinces.get("Erzincan").add("Üzümlü");
        districtsOfProvinces.get("Trabzon").add("Vakfıkebir");
        districtsOfProvinces.get("Muş").add("Varto");
        districtsOfProvinces.get("Samsun").add("Vezirköprü");
        districtsOfProvinces.get("Şanlıurfa").add("Viranşehir");
        districtsOfProvinces.get("Kırklareli").add("Vize");
        districtsOfProvinces.get("Giresun").add("Yağlıdere");
        districtsOfProvinces.get("Kırıkkale").add("Yahşihan");
        districtsOfProvinces.get("Kayseri").add("Yahyalı");
        districtsOfProvinces.get("Samsun").add("Yakakent");
        districtsOfProvinces.get("Erzurum").add("Yakutiye");
        districtsOfProvinces.get("Konya").add("Yalıhüyük");
        districtsOfProvinces.get("Yalova").add("Yalova");
        districtsOfProvinces.get("Isparta").add("Yalvaç");
        districtsOfProvinces.get("Çankırı").add("Yapraklı");
        districtsOfProvinces.get("Muğla").add("Yatağan");
        districtsOfProvinces.get("Gaziantep").add("Yavuzeli");
        districtsOfProvinces.get("Hatay").add("Yayladağı");
        districtsOfProvinces.get("Bingöl").add("Yayladere");
        districtsOfProvinces.get("Malatya").add("Yazıhan");
        districtsOfProvinces.get("Bingöl").add("Yedisu");
        districtsOfProvinces.get("Çanakkale").add("Yenice");
        districtsOfProvinces.get("Karabük").add("Yenice");
        districtsOfProvinces.get("Bolu").add("Yeniçağa");
        districtsOfProvinces.get("Yozgat").add("Yenifakılı");
        districtsOfProvinces.get("Ankara").add("Yenimahalle");
        districtsOfProvinces.get("Aydın").add("Yenipazar");
        districtsOfProvinces.get("Bilecik").add("Yenipazar");
        districtsOfProvinces.get("Isparta").add("Yenişarbademli");
        districtsOfProvinces.get("Bursa").add("Yenişehir");
        districtsOfProvinces.get("Diyarbakır").add("Yenişehir");
        districtsOfProvinces.get("Mersin").add("Yenişehir");
        districtsOfProvinces.get("Yozgat").add("Yerköy");
        districtsOfProvinces.get("Kayseri").add("Yeşilhisar");
        districtsOfProvinces.get("Mardin").add("Yeşilli");
        districtsOfProvinces.get("Burdur").add("Yeşilova");
        districtsOfProvinces.get("Malatya").add("Yeşilyurt");
        districtsOfProvinces.get("Tokat").add("Yeşilyurt");
        districtsOfProvinces.get("Düzce").add("Yığılca");
        districtsOfProvinces.get("Bursa").add("Yıldırım");
        districtsOfProvinces.get("Sivas").add("Yıldızeli");
        districtsOfProvinces.get("Trabzon").add("Yomra");
        districtsOfProvinces.get("Yozgat").add("Yozgat");
        districtsOfProvinces.get("Adana").add("Yumurtalık");
        districtsOfProvinces.get("Konya").add("Yunak");
        districtsOfProvinces.get("Manisa").add("Yunusemre");
        districtsOfProvinces.get("Artvin").add("Yusufeli");
        districtsOfProvinces.get("Hakkâri").add("Yüksekova");
        districtsOfProvinces.get("Adana").add("Yüreğir");
        districtsOfProvinces.get("Sivas").add("Zara");
        districtsOfProvinces.get("İstanbul").add("Zeytinburnu");
        districtsOfProvinces.get("Tokat").add("Zile");
        districtsOfProvinces.get("Zonguldak").add("Zonguldak");
        districtsOfProvinces.get("Artvin").add("Kemalpaşa");
        districtsOfProvinces.get("Aksaray").add("Sultanhanı");
        comboProvince.getItems().setAll(provinces);
        */
    }

}
